<?php

namespace App\Application\Services;

use App\Domain\Booking\Booking;
use App\Domain\Booking\BookingHold;
use App\Domain\Booking\BookingStatus;
use App\Domain\Calendar\CalendarConnectionStatus;
use App\Domain\Location\Location;
use App\Domain\Resource\Resource;
use App\Domain\Schedule\ScheduleExceptionType;
use App\Domain\Schedule\ScheduleRule;
use App\Domain\Service\Service;
use Carbon\CarbonImmutable;
use Carbon\CarbonInterface;
use DateTimeZone;
use Illuminate\Support\Collection;

/**
 * Computes bookable slots (§17) from schedule_rules + schedule_exceptions,
 * minus resource_blocks, active bookings and active booking_holds, minus
 * the organization's minimum-notice window, honoring each service's
 * buffer_before/after. Capacity (party_size > 1 concurrent bookings) is
 * out of scope — deferred to Phase 4 alongside the rest of capacity
 * booking, so any active booking/hold fully blocks a resource.
 *
 * Slots are generated by stepping through each working interval in
 * increments of the service's duration — a simplification versus letting
 * customers pick any finer-grained start time, but keeps the algorithm and
 * its output predictable.
 */
class AvailabilityService
{
    public function __construct(private readonly AvailabilityCache $cache) {}

    /**
     * @return array<int, array{date: string, slots: array<int, array{start: string, end: string, resource_id: string}>}>
     */
    public function forService(
        Service $service,
        ?Location $location,
        ?Resource $onlyResource,
        CarbonImmutable $dateFrom,
        CarbonImmutable $dateTo,
        string $timezone,
        int $partySize,
    ): array {
        $dateTo = $this->clampToMaxHorizon($service, $dateTo);

        if ($dateTo->lt($dateFrom)) {
            return [];
        }

        $resources = $this->eligibleResources($service, $location, $onlyResource, $partySize);

        /** @var array<string, array<int, array{start: string, end: string, resource_id: string}>> $byDate */
        $byDate = [];

        foreach ($resources as $resource) {
            $days = $this->cache->remember(
                $resource,
                $service,
                $dateFrom,
                $dateTo,
                $timezone,
                fn () => $this->computeForResource($resource, $service, $dateFrom, $dateTo, $timezone),
            );

            foreach ($days as $date => $slots) {
                $byDate[$date] = array_merge($byDate[$date] ?? [], $slots);
            }
        }

        ksort($byDate);

        $result = [];

        foreach ($byDate as $date => $slots) {
            usort($slots, fn ($a, $b) => $a['start'] <=> $b['start']);
            $result[] = ['date' => $date, 'slots' => $slots];
        }

        return $result;
    }

    /**
     * @return array<string, array<int, array{start: string, end: string, resource_id: string}>>
     */
    private function computeForResource(Resource $resource, Service $service, CarbonImmutable $dateFrom, CarbonImmutable $dateTo, string $timezone): array
    {
        $tz = new DateTimeZone($timezone);

        $rulesByDay = $resource->scheduleRules()->get()->groupBy('day_of_week');

        // whereDate() (not a plain where()/whereBetween() on the column)
        // matters here: SQLite has no native DATE type, so a 'date' cast
        // column is stored as "Y-m-d 00:00:00" — a raw string comparison
        // against a bare "Y-m-d" bound sorts it as "greater than" and
        // silently misses every row. whereDate() wraps both sides in a
        // SQL DATE() function, which is correct on both SQLite and
        // PostgreSQL.
        $exceptionsByDate = $resource->scheduleExceptions()
            ->whereDate('date', '>=', $dateFrom->toDateString())
            ->whereDate('date', '<=', $dateTo->toDateString())
            ->get()
            ->keyBy(fn ($e) => $e->date->toDateString());

        $rangeStart = $dateFrom->setTimezone($tz)->startOfDay();
        $rangeEnd = $dateTo->setTimezone($tz)->endOfDay();

        $blocks = $resource->blocks()
            ->where('starts_at', '<', $rangeEnd)
            ->where('ends_at', '>', $rangeStart)
            ->get(['starts_at', 'ends_at']);

        $bookings = Booking::query()
            ->where('resource_id', $resource->id)
            ->whereIn('status', array_map(fn (BookingStatus $s) => $s->value, BookingStatus::active()))
            ->where('start_at', '<', $rangeEnd)
            ->where('end_at', '>', $rangeStart)
            ->with('service:id,buffer_before_minutes,buffer_after_minutes')
            ->get(['start_at', 'end_at', 'service_id']);

        $holds = BookingHold::query()
            ->where('resource_id', $resource->id)
            ->where('expires_at', '>', now())
            ->where('start_at', '<', $rangeEnd)
            ->where('end_at', '>', $rangeStart)
            ->with('service:id,buffer_before_minutes,buffer_after_minutes')
            ->get(['start_at', 'end_at', 'service_id']);

        // Each occupied booking/hold is widened by its OWN service's
        // buffers, not the candidate's — buffer_after is the resource's
        // cleanup/prep time around THAT appointment regardless of what
        // gets booked next to it. The candidate is then checked against
        // these widened ranges using its raw span (see
        // slotsWithinInterval): once a candidate itself becomes a
        // booking, its own buffers protect it the same way for future
        // computations.
        $occupied = $bookings->map(fn ($b) => [
            $b->start_at->subMinutes($b->service->buffer_before_minutes),
            $b->end_at->addMinutes($b->service->buffer_after_minutes),
        ])->concat($holds->map(fn ($h) => [
            $h->start_at->subMinutes($h->service->buffer_before_minutes),
            $h->end_at->addMinutes($h->service->buffer_after_minutes),
        ]))->concat($blocks->map(fn ($b) => [$b->starts_at, $b->ends_at]))
            ->concat($this->calendarBusyPeriods($resource, $rangeStart, $rangeEnd));

        $minStart = now()->addMinutes((int) ($resource->organization->settings['booking_min_notice_minutes'] ?? 0));

        /** @var array<string, array<int, array{start: string, end: string, resource_id: string}>> $result */
        $result = [];

        for ($cursor = $dateFrom->setTimezone($tz)->startOfDay(); $cursor->lte($dateTo); $cursor = $cursor->addDay()) {
            $dateKey = $cursor->toDateString();
            $exception = $exceptionsByDate->get($dateKey);

            if ($exception?->type === ScheduleExceptionType::Closed) {
                continue;
            }

            $intervals = $exception?->type === ScheduleExceptionType::CustomHours
                ? [[$exception->start_time, $exception->end_time]]
                : $this->intervalsFromRules($rulesByDay, $cursor);

            foreach ($intervals as [$startTime, $endTime]) {
                $slots = $this->slotsWithinInterval(
                    $resource, $service, $dateKey, $startTime, $endTime, $tz, $occupied, $minStart,
                );

                if ($slots !== []) {
                    $result[$dateKey] = array_merge($result[$dateKey] ?? [], $slots);
                }
            }
        }

        return $result;
    }

    /**
     * §37: busy periods on the resource's connected external calendar
     * (§36) count as occupied the same as an internal booking, using
     * whatever RefreshCalendarBusyPeriods last cached on the
     * connection (§62 refreshes this every 5 minutes) -- this never
     * calls the provider directly on the request path.
     *
     * @return array<int, array{0: CarbonInterface, 1: CarbonInterface}>
     */
    private function calendarBusyPeriods(Resource $resource, CarbonInterface $rangeStart, CarbonInterface $rangeEnd): array
    {
        $connection = $resource->calendarConnection;

        if ($connection === null || $connection->status !== CalendarConnectionStatus::Active) {
            return [];
        }

        return collect($connection->busy_periods ?? [])
            ->map(fn (array $period) => [
                CarbonImmutable::parse($period['start']),
                CarbonImmutable::parse($period['end']),
            ])
            ->filter(fn (array $period) => $period[0]->lt($rangeEnd) && $period[1]->gt($rangeStart))
            ->values()
            ->all();
    }

    /**
     * @param  Collection<int|string, Collection<int, ScheduleRule>>  $rulesByDay
     * @return array<int, array{0: string, 1: string}>
     */
    private function intervalsFromRules(Collection $rulesByDay, CarbonImmutable $day): array
    {
        $dateString = $day->toDateString();

        return ($rulesByDay->get($day->dayOfWeek) ?? collect())
            ->filter(function ($rule) use ($dateString) {
                $afterStart = ! $rule->valid_from || $dateString >= $rule->valid_from->toDateString();
                $beforeEnd = ! $rule->valid_until || $dateString <= $rule->valid_until->toDateString();

                return $afterStart && $beforeEnd;
            })
            ->map(fn ($rule) => [substr((string) $rule->start_time, 0, 5), substr((string) $rule->end_time, 0, 5)])
            ->values()
            ->all();
    }

    /**
     * @param  Collection<int, array{0: CarbonInterface, 1: CarbonInterface}>  $occupied
     * @return array<int, array{start: string, end: string, resource_id: string}>
     */
    private function slotsWithinInterval(
        Resource $resource,
        Service $service,
        string $dateKey,
        string $startTime,
        string $endTime,
        DateTimeZone $tz,
        Collection $occupied,
        CarbonInterface $minStart,
    ): array {
        $intervalStart = CarbonImmutable::parse("{$dateKey} {$startTime}", $tz);
        $intervalEnd = CarbonImmutable::parse("{$dateKey} {$endTime}", $tz);

        $slots = [];
        $slotStart = $intervalStart;

        while ($slotStart->addMinutes($service->duration_minutes)->lte($intervalEnd)) {
            $slotEnd = $slotStart->addMinutes($service->duration_minutes);

            if ($slotStart->gte($minStart)) {
                $blocked = $occupied->contains(fn ($range) => $range[0]->lt($slotEnd) && $range[1]->gt($slotStart));

                if (! $blocked) {
                    $slots[] = [
                        'start' => $slotStart->toIso8601String(),
                        'end' => $slotEnd->toIso8601String(),
                        'resource_id' => $resource->public_id,
                    ];
                }
            }

            $slotStart = $slotEnd;
        }

        return $slots;
    }

    /**
     * Whether [startAt, endAt) falls entirely inside one of the
     * resource's open working intervals for that day — schedule_rules,
     * or schedule_exceptions if one exists for the date (§17). This is
     * the check BookingService::create()/reschedule() were missing: a
     * booking could previously be created outside business hours
     * entirely by calling /bookings directly instead of picking a slot
     * from /availability first. Deliberately independent of existing
     * bookings/holds/blocks — those are checked separately.
     */
    public function isWithinWorkingHours(Resource $resource, CarbonInterface $startAt, CarbonInterface $endAt): bool
    {
        $tz = new DateTimeZone($resource->location?->timezone ?? $resource->organization->timezone);

        $localStart = CarbonImmutable::instance($startAt)->setTimezone($tz);
        $localEnd = CarbonImmutable::instance($endAt)->setTimezone($tz);
        $dateKey = $localStart->toDateString();

        $exception = $resource->scheduleExceptions()->whereDate('date', $dateKey)->first();

        if ($exception?->type === ScheduleExceptionType::Closed) {
            return false;
        }

        $intervals = $exception?->type === ScheduleExceptionType::CustomHours
            ? [[substr((string) $exception->start_time, 0, 5), substr((string) $exception->end_time, 0, 5)]]
            : $this->intervalsFromRules($resource->scheduleRules()->get()->groupBy('day_of_week'), $localStart);

        foreach ($intervals as [$startTime, $endTime]) {
            $intervalStart = CarbonImmutable::parse("{$dateKey} {$startTime}", $tz);
            $intervalEnd = CarbonImmutable::parse("{$dateKey} {$endTime}", $tz);

            if ($localStart->gte($intervalStart) && $localEnd->lte($intervalEnd)) {
                return true;
            }
        }

        return false;
    }

    /**
     * @return Collection<int, resource>
     */
    private function eligibleResources(Service $service, ?Location $location, ?Resource $onlyResource, int $partySize): Collection
    {
        if ($onlyResource) {
            return collect([$onlyResource]);
        }

        return $service->resources()
            ->when($location, fn ($q) => $q->where('resources.location_id', $location->id))
            ->where('resources.capacity', '>=', $partySize)
            ->get();
    }

    private function clampToMaxHorizon(Service $service, CarbonImmutable $dateTo): CarbonImmutable
    {
        $maxDaysAhead = (int) ($service->organization->settings['booking_max_days_ahead'] ?? 90);
        $horizon = CarbonImmutable::now()->addDays($maxDaysAhead)->endOfDay();

        return $dateTo->gt($horizon) ? $horizon : $dateTo;
    }
}
